name: social_app
description: A LinkedIn-style social networking app
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.5

  # Networking
  http: ^1.4.0

  # Secure token storage
  flutter_secure_storage: ^4.2.1

  # UI icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
